CREATE TABLE IF NOT EXISTS Submission (
  id SERIAL PRIMARY KEY,
  owner VARCHAR(64) NOT NULL,
  content TEXT NOT NULL,
  language_id VARCHAR(40) NOT NULL,
  submitted_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP),
  verdict VARCHAR(256) NOT NULL
);